<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Processo Seletivo</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-cadastrar-processo-seletivo.css">
    
</head>

<body>

    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" href="/home">Home</a>
                        <a class="nav-link" href="/#">Funcionário</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/teste_candidato">Testes</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
    </nav>

    <?php
    if (isset($_GET['cadastroProcSeletivo'])) {
    ?>

        <script>
            alert("Cadastro do processo seletivo realizado com sucesso!");
        </script>

    <?php
    header("Location: /gerenciar_processo_seletivo");}
    ?>

    <form action="/processo_seletivo_cadastrar" method="post">
        <div class="container">
            <div class="title">
                <h1 class="title-1">Cadastrar Processo Seletivo</h1>
            </div>

            <div class="title">
                <h2 class="title-2">Dados de Cadastro</h2>
                <img class="info" src="/images/global/info.svg">
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form" id="colFormLabel" placeholder="" name="tituloProcSeletivo" required>
                </div>
            </div>

            <div class="row mb-3">
                <label for="vacancy" class="col-sm-2 form-label form-label">Vaga</label>
                <div class="col-sm-10">
                    <select class="col form-select form" name="vacancy" required>
                        <option selected></option>
                        <option value="1">#</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="responsible" class="col-sm-2 form-label form-label">Responsável</label>
                <div class="col-sm-10">
                <select class="col form-select" name="responsible" required>
                            <option selected></option>
                            <?php foreach ($this->view->usuarios as $key => $usuario) { ?>
                                <option value="<?=$usuario->id_user?>"><?= $usuario->nome ?></option>
                            <?php } ?>
                    </select>
                </div>
            </div>

            <div class="title">
                <h2 class="title-2">Dados do Processo</h2>
                <img class="info" src="/images/global/info.svg">
            </div>

            <div class="row mb-3">
                <div class="row mb-3">
                    <label for="start_date" class="col-sm-2 form-label form-label">Data de Início</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control form" name="start_date" required>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="end_date" class="col-sm-2 form-label form-label">Data de Término</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control form" name="end_date" required>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Classificação</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="colFormLabel" placeholder="%" name="classification-rule" min="0" step="5" max="100" required>  
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Descrição</label>
                    <textarea type="text" class="form-control text-area" name="descProc" required></textarea>
                </div>
            </div>

            <a href="/atribuir_teste" class="btn btn-outline-primary">Atribuir Teste</a>

            <hr />

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5" onclick="window.location.href = '/gerenciar_processo_seletivo'">Voltar</button>
                <button type="submit" class="btn btn-outline-primary mb-5">Cadastrar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

        <script src="/scripts/general-scripts/processo-seletivo.js"></script>
</body>

</html>